services:

  user_service:
    image: user_service

    ports:
      - "8080"

    depends_on:
      - mongodb

    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/hotelsDB

    deploy:
      replicas: 2

  booking_service:
    image: booking_service

    ports:
      - "8080"

    depends_on:
      - mongodb

    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/hotelsDB

    deploy:
      replicas: 2

  search_service:
    image: search_service

    ports:
      - "8080"

    depends_on:
      - mongodb
      - redis

    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/hotelsDB

    deploy:
      replicas: 2

  mongodb:
    image: mongo:7
    container_name: mongodb

    ports:
      - "27017:27017"

    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:7-alpine
    container_name: redis

    ports:
      - "6379:6379"

    volumes:
      - redis-data:/data/cache

  nginx:
    image: nginx:latest

    ports:
      - "3000:80"

    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

    depends_on:
      - user_service
      - booking_service
      - search_service

volumes:
  mongo-data:
  redis-data: