services:

  user_service:
    build: .

    ports:
      - "8080"

    depends_on:
      - mongodb

    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/hotelsDB

    deploy:
      replicas: 3

  booking_service:
    build: .

    ports:
      - "8080"

    depends_on:
      - mongodb

    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/hotelsDB

    deploy:
      replicas: 3

  search_service:
    build: .

    ports:
      - "8080"

    depends_on:
      - mongodb

    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/hotelsDB

    deploy:
      replicas: 3

  mongodb:
    image: mongo:7
    container_name: mongodb

    ports:
      - "27017:27017"

    volumes:
      - mongo-data:/data/db

  nginx:
    image: nginx:latest

    ports:
      - "3000:80"

    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

    depends_on:
      - hotel-booking

volumes:
  mongo-data: