services:

  user_service:
    image: user-service:latest
#    container_name: user-service:latest

    ports:
      - "8080"

    depends_on:
      - mongodb

    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/hotelsDB

    deploy:
      replicas: 2

  booking_service:
    image: booking-service:latest
#    container_name: booking-service:latest

    ports:
      - "8080"

    depends_on:
      - mongodb

    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/hotelsDB

    deploy:
      replicas: 2

  search_service:
    image: search-service:latest
#    container_name: search-service:latest

    ports:
      - "8080"

    depends_on:
      - mongodb

    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/hotelsDB

    deploy:
      replicas: 2

  mongodb:
    image: mongo:7
    container_name: mongodb

    ports:
      - "27017:27017"

    volumes:
      - mongo-data:/data/db

  nginx:
    image: nginx:latest

    ports:
      - "3000:80"

    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

    depends_on:
      - user_service
      - booking_service
      - search_service

volumes:
  mongo-data: