events {}

http {

    upstream user-service-app{
        server user-service:8080;
    }

    upstream booking-service-app {
        server booking-service:8080;
    }

    upstream search-service-app {
        server search-service:8080;
    }

    server {

        listen 80;

        location /api/users {
            proxy_pass http://user-service-app;
        }

        location /api/bookings {
            proxy_pass http://booking-service-app;
        }

        location /api/search {
            proxy_pass http://search-service-app;
        }
    }
}