events {}

http {
    upstream search-service-app {
        server search_service:8080;
    }

    upstream user-service-app{
        server user_service:8080;
    }

    upstream booking-service-app {
        server booking_service:8080;
    }

    server {
        listen 80;

        location /api/users {
             proxy_pass http://user-service-app;
        }

        location /api/search {
             proxy_pass http://search-service-app;
        }

        location /api/bookings {
            proxy_pass http://booking-service-app;
        }

    }
}